### ISSUE TITLE
TOC should stay at the top via a sticky div

### ISSUE THREAD

**Issue by terracatta** [kolide/osquery-site#38]
![image](https://user-images.githubusercontent.com/315873/33721516-42e8b0b6-db35-11e7-9be8-6a1e3a03e491.png)

See screenshot above, but basically the behavior I am looking for is that the TOC does not move until it _must_ move to remain visible on the screen (standard sticky menu).

**Comment by taylorkearns** [comment]
@mikestone14 thinking through how to achieve this. We could set state, say `fixedTOC: true` if the scroll position of the TOC is at a certain point, and false otherwise, but how do we get around constantly setting state? Must be a cleaner solution.
