### ISSUE TITLE
Add Favicons

### ISSUE THREAD

**Issue by terracatta** [kolide/osquery-site#39]
Let's ensure we have proper favicon and favicon metatags before the site launches. The existing favicons on osquery.io can be used for this.

**Comment by honestcomrade** [comment]
how many platforms need to be supported? just the standard browser sizes? or are you looking for apple touch, android, etc?

**Comment by terracatta** [comment]
> how many platforms need to be supported? just the standard browser sizes? or are you looking for apple touch, android, etc?

I think there is a generator that does all the platforms possibly if you submit a high-enough quality image (which we can supply), so we should just use that.

**Comment by mikestone14** [comment]
@terracatta do you have the image for the favicon?
