### ISSUE TITLE
Footer fixes

### ISSUE THREAD

**Issue by terracatta** [kolide/osquery-site#40]
I'd like to fix the following things in the footer.

- [x] Remove "In loving memory of Parse"
- [x] Link the 2017 Project License to the following page (opens in a new window) https://github.com/facebook/osquery/blob/master/LICENSE
- [x] Link the word "Kolide" to https://kolide.com (opens in a new window) 
- [x] Link "Facebook Open Source" to https://code.facebook.com/projects/ (opens in a new window)

**Comment by mikestone14** [comment]
closed by #57
