### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by terracatta** [kolide/osquery-site#41]
When a page does not have enough content, the footer floats above the bottom of the page. I'd like to implement a standard sticky footer where if the page does not have enough content the footer is always at the bottom of the browser viewport, but if it does, the footer will lay underneath the content.

Example of this bug below...

![image](https://user-images.githubusercontent.com/315873/33721855-332a5d72-db36-11e7-9b5c-4f21e422a741.png)

**Comment by mikestone14** [comment]
Closed by #59
