### ISSUE TITLE
Issue with dropdown

### ISSUE THREAD

**Issue by FritzX6** [kolide/osquery-site#80]
Post #77 the text in the dropdown is no longer centered and now cut-off when active.

- [x] Fix centering and visual-cutoff of text in dropdown input field.

**Screenshot:**
![image](https://user-images.githubusercontent.com/931724/33966359-5509a9d8-e02d-11e7-9a73-dc942e816ff8.png)

**Comment by taylorkearns** [comment]
Closed by #77
